# _*_ encoding:utf-8 _*_

"""
Django settings for MxOnline project.

Generated by 'django-admin startproject' using Django 1.9.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os
import sys

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
#项目的根目录
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(BASE_DIR, 'apps'))
sys.path.insert(0, os.path.join(BASE_DIR, 'extra_apps'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
#安全码
SECRET_KEY = '6-_!diub7+edip4y_a$tp(bu7*0z2)ha%z7^ii0gju$8$@=0c_'

# SECURITY WARNING: don't run with debug turned on in production!
#值为True的时候，404页面是不起作用的，在生产环境部署的时候必须改成False
DEBUG = True

#DEBUG模式下为空，生产模式下必须有值(允许连接的IP地址)
# ALLOWED_HOSTS = []
ALLOWED_HOSTS = ['*']

# Application definition
AUTHENTICATION_BACKENDS=(
    'users.views.CustomBackend',
)

#已安装的应用
INSTALLED_APPS = [
    'django.contrib.admin',         #管理后台
    'django.contrib.auth',          #身份验证系统
    'django.contrib.contenttypes',  #内容类型框架
    'django.contrib.sessions',      #会话框架
    'django.contrib.messages',      #消息框架
    'django.contrib.staticfiles',   #管理静态文件的框架
    'users',
    'courses',
    'organization',
    'operation',
    'xadmin',
    'crispy_forms',
    'captcha',
    'pure_pagination',

]
AUTH_USER_MODEL = "users.UserProfile"

#中间件，django自带的工具集
MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

#告诉django，网站的URL配置在哪个Python模块中
#url的根文件
ROOT_URLCONF = 'MxOnline.urls'

#模板的配置
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.core.context_processors.media',
            ],
        },
    },
]


WSGI_APPLICATION = 'MxOnline.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

#数据库配置
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': "mxonline",
        'USER': "root",
        'PASSWORD': "mysql123",
        'HOST': "127.0.0.1",
        'OPTIONS': {
            'init_command': 'SET foreign_key_checks = 0;',
        }
    }
}

# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

#设置语言
LANGUAGE_CODE = 'zh-hans'

#设置时区，可设置本地时间
TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

#静态文件地址
STATIC_URL = '/static/'
STATICFILES_DIRS=(
    os.path.join(BASE_DIR,"static"),
)

EMAIL_HOST="smtp.sina.com"
EMAIL_PORT=25
EMAIL_HOST_USER="seventeen_1717@sina.com"
EMAIL_HOST_PASSWORD="seventeen1717"
EMAIL_USE_TLS=False
EMAIL_FROM="seventeen_1717@sina.com"

MEDIA_URL='/media/'
MEDIA_ROOT=os.path.join(BASE_DIR,'media')

# STATIC_ROOT=os.path.join(BASE_DIR,'static')
